import 'package:flutter/material.dart';

const Map<String, IconData> categoryIconMap = {
  'restaurant': Icons.restaurant,
  'directions_car': Icons.directions_car,
  'movie': Icons.movie,
  'child_care': Icons.child_care,
  'face': Icons.face,
  'receipt': Icons.receipt,
  'directions_car_filled': Icons.directions_car_filled,
  'checkroom': Icons.checkroom,
  'school': Icons.school,
  'devices': Icons.devices,
  'emoji_events': Icons.emoji_events,
  'local_offer': Icons.local_offer,
  'confirmation_number': Icons.confirmation_number,
  'replay': Icons.replay,
  'house': Icons.house,
  'work': Icons.work,
  'trending_up': Icons.trending_up,
  'health': Icons.favorite,
  'home': Icons.home,
  'insurance': Icons.shield,
  'shopping': Icons.shopping_cart,
  'social': Icons.people,
  'sport': Icons.sports_tennis,
  'tax': Icons.account_balance,
  'telephone': Icons.phone,
  'category': Icons.category,
  'shopping_bag_outlined': Icons.shopping_bag_outlined,
  'directions_bus_filled_outlined': Icons.directions_bus_filled_outlined,
  'movie_outlined': Icons.movie_outlined,
  'receipt_long_outlined': Icons.receipt_long_outlined,
  'shopping_basket': Icons.shopping_basket,
};
